name = "Modify"
client_id = "036ad79f1507855e201e76b608681770"
application_url = "https://modify-coral.vercel.app"
embedded = false

[auth]
redirect_urls = [
  "https://modify-coral.vercel.app/api/shopify/callback",
  "http://localhost:3000/api/shopify/callback"
]

[access_scopes]
scopes = "read_themes,write_themes,read_products,write_products,read_analytics,write_content,read_content,read_orders"

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://modify-coral.vercel.app/api/webhooks/customers/data_request"
  customer_deletion_url = "https://modify-coral.vercel.app/api/webhooks/customers/redact"
  shop_deletion_url = "https://modify-coral.vercel.app/api/webhooks/shop/redact"
