-- Migration 009: SEO blog articles generated by Modify

create table if not exists blog_articles (
  id uuid primary key default uuid_generate_v4(),
  store_id uuid references stores(id) on delete cascade,
  blog_id bigint,
  article_id bigint,
  title text not null,
  handle text,
  url text,
  tags text,
  created_at timestamptz default now() not null
);

alter table blog_articles enable row level security;

create policy "Users can view own blog articles"
  on blog_articles for select
  using (
    store_id in (select id from stores where user_id = auth.uid()::text)
  );

drop policy if exists "Service role insert blog articles" on blog_articles;
create policy "Service role insert blog articles"
  on blog_articles for insert
  with check (true);

create index if not exists idx_blog_articles_store on blog_articles (store_id, created_at desc);

notify pgrst, 'reload schema';
